export const GET_DATA = "GET_DATA";
export const SELECT_CURRENCY = "SELECT_CURRENCY";
export const ADD_CURRENCY = "ADD_CURRENCY";
export const UPDATE_CURRENCIES = "UPDATE_CURRENCIES";
export const REMOVE_CURRENCY = "REMOVE_CURRENCY";
export const UPDATE_FAVORITES = "UPDATE_FAVORITES";
